# These settings are synced to GitHub by https://github.com/github/safe-settings

repository:
  force_create: true
  homepage: https://github.com/gi-tops/safe-settings
  auto_init: true
  topics:
    - github
    - safe-settings
  private: false
  visibility: public
  has_issues: true
  has_projects: true
  has_wiki: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true

teams:
  - name: core
    permission: admin
  - name: docs
    permission: push
  - name: read
    permission: pull
  - name: globalteam
    permission: push
    visibility: closed

branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: ['core']
      # required_status_checks:
      #   strict: true
      #   contexts: []
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: [core, docs, globalteam]

validator:
  pattern: '[a-zA-Z0-9_-]+'

restrictedRepos:
  exclude: ['admin', '.github', 'safe-settings']
