name: GitHub Script Workflow
on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Starting the script...");
            console.log("Hello, this is a message from the GitHub Script Workflow!");
            console.log("Ending the script.");
            return 1
  error-message:
    runs-on: ubuntu-latest
    steps:
      - name: Errors a message
        uses: actions/github-script@v7
        with:
          script: |
            console.setFailed("exits and errors");
            console.warn("boo");
            console.error("crap");
            console.log("Ending the script.");
